name = "alsania-io-site"
compatibility_date = "2026-08-01"

[pages]
build = { command = "npm run build" }

[env.production]
[env.production.pages]
build = { command = "npm run build", output_dir = "dist" }